WEIGHT = 5.5
epsilon = 1
DRAW = False
#HOST = 'agentcontest1.in.tu-clausthal.de'
#HOST = 'rvince.in.tu-clausthal.de'
#HOST = 'rb02.in.tu-clausthal.de'
HOST = 'localhost'
#HOST = '192.168.0.13'
MAX_PROBE_STEPS = 150 # probes will only be in zone and sentinels stop survey after this
EXTRA_PROBE_STEPS = 50 # probes will only be in zone and sentinels stop survey after this
MAX_SURVEY_STEPS = 30 # only surveyers will survey from this step
MAX_ATTACK_WEAK_STEPS = 80 # will start attaking repairers and saboteurs from here
NUM_OF_AGENTS = 28
PASSWORD = '1'

MAX_EDGE_WEIGHT = 10
REP = 'Repairer'
SEN = 'Sentinel'
SAB = 'Saboteur'
EXP = 'Explorer'
INS = 'Inspector'
PRICE = 2
BFS_ROUNDS = 400
NOOP_COST = 500
NUM_OF_EACH = 4
NOOP = 'skip'
ATTACK = 'attack'
INSPECT = 'inspect'
SURVEY = 'survey'
REPAIR = 'repair'
GOTO = 'goto'
RECHARGE = 'recharge'
PROBE = 'probe'
PARRY = 'parry'
BUY = 'buy'
STRENGTH = 'sabotageDevice'
HEALTH = 'shield'
INITIAL_MAX_STRENGTH = 3
INITIAL_MAX_HEALTH = 3
RECHARGE_DIS = 0.7
RECHARGE_EN = 0.5

COSTS = { ATTACK : 2, INSPECT : 2, SURVEY : 1, REPAIR : 2, PROBE : 1, GOTO : 0, PARRY : 2, NOOP : 2 }
RUN = True
