#!/bin/sh

# this file was generated by mas2j parser

export PATH=/System/Library/Frameworks/JavaVM.framework/Versions/1.4.2/Home/bin:$PATH

echo -n "        compiling user classes..."
# compile files [mds/MDSAgent, cph/CPHAgent, HeathrowEnv, cph/CPHAgArch]
# on [cph, mds, .]
javac -classpath .:"/Users/jomi/programming/cvs/Jason/bin/jason.jar":"/Users/jomi/programming/cvs/Jason/lib/saci/bin/saci.jar":"/Users/jomi/programming/cvs/Jason/lib/log4j.jar":"/Users/jomi/programming/agents/Jason-applications/HeathrowRobotsFor0.7":"$CLASSPATH"  cph/*.java mds/*.java ./*.java

chmod u+x *.sh
echo ok
